name: VanishSystem
main: JuanantonioVYT\VanishSystem\Main
author: JuanantonioVYT
api: 3.25.0
version: 1.0

commands:
  vanish:
    description: "Disappear"
  unvanish:
    description: "Appear"
  vanishabout:
    description: "About This Plugin"