name: VanishSystem
main: JuanantonioVYT\VanishSystem\Main
author: JuanantonioVYT
api: 3.25.0
version: 1.0

commands:
  vanish:
    description: "You are Vanished"
    
  unvanish:
    description: "You are unvanished"
  
  vanishabout:
    description: "About This Plugin"
