#Plugin VanishSystem Made By JuanantonioVYT Configurable#

msg-vanish: "ยง9You have been successfully Vanished!"
msg-unvanish: "ยง9You have been successfully Unvanished!"

#Plugin VanishSystem Made By JuanantonioVYT Configurable#